Use babel/semi
zeroturnaround/eslint-config-zt pull request #10
Opened 2017-05-30 19:12 UTC by jseminck

Use babel/semi instead of eslint semi.

The reason is that babel/semi also supports semi-colon enforcing on class properties. Eslint semi does not support this because class properties are only at stage-2 and eslint only wants to support features which are finalised.

eslint-plugin-babel implements rules for babel-specific features that are stage0-3, though there are not many rules there: https://github.com/babel/eslint-plugin-babel

2017-05-31 06:33 UTC, ukupat requested changes
@jseminck – you have two issues in your changes that make index.js and package.json invalid. Also we should update README.md about babel ruleset.

2017-05-31 06:33 UTC, ukupat commented on package.json
> +    "eslint-plugin-react": ">=6.7.0"
This causes an error in Travis, please fix it.

2017-05-31 06:33 UTC, ukupat commented on index.js
> +        './babel.js'
You are missing a comma.

2017-05-31 06:45 UTC, jseminck commented
Fixed the bugs. My bad - had some clashes with the other PR.

What exactly to add to the readme? The `babel/semi` covers (or should cover) the same functionality as the eslint `semi` rule, but adds the extra checks for the class properties.

2017-05-31 07:25 UTC, ukupat commented
@jseminck – about README: for example SQL Formatter does not use React, therefore it needs to extend "zt/base" and "zt/babel" rulesets. Right now README only informs users about "zt/base" ruleset.

2017-05-31 07:42 UTC, jseminck commented
Hmm - good point. Maybe this rule should just be a part of the `zt/base` as I believe it should also work (applying the default semi-colon rule) if the user is not using babel or any ES7 features. 

I would need to test to confirm this though.

2017-06-12 12:30 UTC, ukupat commented
@jseminck – did you test it?

2017-06-12 17:55 UTC, jseminck commented
I think it's better not to add this. Not worth the added complexity.

2017-06-13 06:00 UTC, ukupat commented
Alright!

2017-06-13 06:00 UTC, closed without merging