Replace jsx-space-before-closing rule with jsx-tag-spacing
zeroturnaround/eslint-config-zt pull request #9
Opened 2017-05-30 11:35 UTC by jseminck

From 7.0.0 the former rule is deprecated. The functionality is covered by the default values in the latter rule.

Updated peer dependency to 6.7.0.

2017-05-31 06:36 UTC, ukupat requested changes
@jseminck – what do you think about upgrading to the latest eslint-plugin-react version? And updating other dependencies as well?

2017-05-31 06:36 UTC, ukupat commented on react.js
> +        "react/jsx-tag-spacing": 2,
Could you reorder these rules in alphabetical order?

2017-05-31 06:36 UTC, ukupat commented on package.json
> +    "eslint-plugin-react": "^6.7.0"
Why hasn't yarn.lock file changed?

2017-05-31 06:47 UTC, jseminck commented on react.js
> +        "react/jsx-tag-spacing": 2,
The rules aren't in alphabetical order at all :) can create a separate PR afterwards?

2017-05-31 06:50 UTC, jseminck commented
I think it's definitely a good idea to update the versions. Especially v7.0 added warnings for using `React.PropTypes` which we will want when upgrading to React 15.5.

2017-05-31 07:24 UTC, ukupat commented on react.js
> +        "react/jsx-tag-spacing": 2,
Yeah, I noticed that, but now we have a chance to fix it :) A separate PR is also cool, but we should wait this PR to be merged.

2017-06-12 12:29 UTC, ukupat commented
@jseminck – are we going to upgrade eslint-plugin-react to v7?

2017-06-12 17:53 UTC, jseminck commented
I don't know. I do not think it is needed actually. This config should work with 6.4.0 or later, right? I think it's best to put the peerDependency to the lowest version that we can support.

2017-06-13 06:01 UTC, merged